In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
df=pd.read_csv("insurance_data.csv")
df.head()

age  bought_insurance
0   22                 0
1   25                 0
2   47                 1
3   52                 0
4   46                 1

In [14]:
x=df[['age']]

In [15]:
y=df.bought_insurance
y

0     0
1     0
2     1
3     0
4     1
5     1
6     0
7     1
8     1
9     1
10    0
11    0
12    0
13    0
14    1
15    1
16    1
17    1
18    0
19    0
20    0
21    0
22    1
23    1
24    1
25    1
26    0
Name: bought_insurance, dtype: int64

In [16]:
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [19]:
x_train

age
8    62
24   50
13   29
1    25
25   54
22   40
6    55
4    46
19   18
16   25
9    61
7    60
10   18
23   45
26   23
0    22
15   55
3    52
12   27
17   58
21   26

In [21]:
from sklearn import linear_model

In [24]:
model=linear_model.LogisticRegression()

In [28]:
model.fit(x_train,y_train)

LogisticRegression()

In [29]:
x_test

age
18   19
20   21
5    56
14   49
2    47
11   28

In [32]:
model.predict(x_test)


array([0, 0, 1, 1, 1, 0])

In [34]:
model.score(x_test,y_test)

1.0

In [37]:
model.predict_proba(x_test)

array([[0.91065877, 0.08934123],
       [0.89027671, 0.10972329],
       [0.1302463 , 0.8697537 ],
       [0.24968142, 0.75031858],
       [0.29480139, 0.70519861],
       [0.78500916, 0.21499084]])

In [41]:
model.predict([[67]])

array([1])